#!/usr/bin/python3
import os,sys,time
path = os.getcwd()
lista = os.listdir(path)
for i  in lista :
	try:
		print(os.path.abspath(i))
		os.chdir(os.path.join(path,i))
		os.system("git pull")
		os.chdir("..")
	except Exception as e:
		pass
time.sleep(2)
os.system("clear")
print("fim")
